/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author milob
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    int score=0;
    int click=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question = new javax.swing.JLabel();
        reponse1 = new javax.swing.JButton();
        reponse2 = new javax.swing.JButton();
        reponse3 = new javax.swing.JButton();
        reponse4 = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        question.setForeground(new java.awt.Color(255, 0, 0));
        question.setText("quelle est la capitale de l'indonésie ?");
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, -1));

        reponse1.setText("Bali");
        reponse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponse1ActionPerformed(evt);
            }
        });
        getContentPane().add(reponse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 148, -1));

        reponse2.setText("kuala lumpur");
        reponse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponse2ActionPerformed(evt);
            }
        });
        getContentPane().add(reponse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 140, -1));

        reponse3.setText("singapour");
        reponse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponse3ActionPerformed(evt);
            }
        });
        getContentPane().add(reponse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        reponse4.setText("nusantara");
        reponse4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponse4ActionPerformed(evt);
            }
        });
        getContentPane().add(reponse4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        message.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        message.setText("choisissez une réponse");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reponse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponse1ActionPerformed
        // TODO add your handling code here:
        message.setText("faux, c'était Nusantara");
        question.setText("quel club de Londres a le plus de premier league ?");
        reponse1.setText("chelsea");
        reponse2.setText("arsenal");
        reponse3.setText("liverpool");
        reponse4.setText("tottenham");
         click++;
    }//GEN-LAST:event_reponse1ActionPerformed
if click==0:{
    private void reponse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponse3ActionPerformed
        // TODO add your handling code here:
        message.setText("faux, c'était Nusantara");
        question.setText("quel club de Londres a le plus de premier league ?");
        reponse1.setText("chelsea");
        reponse2.setText("arsenal");
        reponse3.setText("liverpool");
        reponse4.setText("tottenham");
        click++;
    }//GEN-LAST:event_reponse3ActionPerformed

    private void reponse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponse2ActionPerformed
        message.setText("faux, c'était Nusantara");  
        question.setText("quel club de Londres a le plus de premier league ?");
        reponse1.setText("chelsea");
        reponse2.setText("arsenal");
        reponse3.setText("liverpool");
        reponse4.setText("tottenham");
        click++;
    }//GEN-LAST:event_reponse2ActionPerformed

    private void reponse4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponse4ActionPerformed
        // TODO add your handling code here:
        message.setText("bonne réponse");
        score=score+1;
        question.setText("quel club de Londres a le plus de premier league ?");
        reponse1.setText("chelsea");
        reponse2.setText("arsenal");
        reponse3.setText("liverpool");
        reponse4.setText("tottenham");
         click++;
    }//GEN-LAST:event_reponse4ActionPerformed
}
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel message;
    private javax.swing.JLabel question;
    private javax.swing.JButton reponse1;
    private javax.swing.JButton reponse2;
    private javax.swing.JButton reponse3;
    private javax.swing.JButton reponse4;
    // End of variables declaration//GEN-END:variables
}
