package miniprojet_cadenas_nom;




import javax.swing.JOptionPane;

    private int[] digits;

    private void updateLabels() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author milob
 */
public class FenetreCadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreCadenas.class.getName());
private CadenasJeu jeu;
    private int[] digits = {0,0,0,0};
    /**
     * Creates new form FenetreCadenas
     */
    public FenetreCadenas() {
        initComponents();
        jeu = new CadenasJeu(10);
        updateLabels();
    }
  private void updateLabels() {
        lblDigit1.setText("" + digits[0]);
        lblDigit2.setText("" + digits[1]);
        lblDigit3.setText("" + digits[2]);
        lblDigit4.setText("" + digits[3]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTester = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblExact = new javax.swing.JLabel();
        lblTropHaut = new javax.swing.JLabel();
        lblTropBas = new javax.swing.JLabel();
        lblNbEssais = new javax.swing.JLabel();
        lblDigit1 = new javax.swing.JLabel();
        lblDigit2 = new javax.swing.JLabel();
        lblDigit3 = new javax.swing.JLabel();
        lblDigit4 = new javax.swing.JLabel();
        btnUp1 = new javax.swing.JButton();
        btnUp2 = new javax.swing.JButton();
        btnUp3 = new javax.swing.JButton();
        btnUp4 = new javax.swing.JButton();
        btnDown1 = new javax.swing.JButton();
        btnDown2 = new javax.swing.JButton();
        btnDown3 = new javax.swing.JButton();
        btnDown4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTester.setText("tester");
        btnTester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesterActionPerformed(evt);
            }
        });

        btnReset.setText("reinitialiser");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblExact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExact.setForeground(new java.awt.Color(51, 255, 51));
        lblExact.setText("correct");

        lblTropHaut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTropHaut.setForeground(new java.awt.Color(255, 255, 0));
        lblTropHaut.setText("haut");

        lblTropBas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTropBas.setForeground(new java.awt.Color(0, 255, 255));
        lblTropBas.setText("bas");

        lblNbEssais.setText("jLabel1");

        lblDigit1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit1.setForeground(new java.awt.Color(255, 51, 51));
        lblDigit1.setText("0");

        lblDigit2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit2.setForeground(new java.awt.Color(255, 51, 51));
        lblDigit2.setText("0");

        lblDigit3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit3.setForeground(new java.awt.Color(255, 51, 51));
        lblDigit3.setText("0");

        lblDigit4.setBackground(new java.awt.Color(255, 0, 0));
        lblDigit4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblDigit4.setForeground(new java.awt.Color(255, 51, 51));
        lblDigit4.setText("0");

        btnUp1.setText("+");
        btnUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUp1ActionPerformed(evt);
            }
        });

        btnUp2.setText("+");
        btnUp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUp2ActionPerformed(evt);
            }
        });

        btnUp3.setText("+");

        btnUp4.setText("+");

        btnDown1.setText("-");

        btnDown2.setText("-");

        btnDown3.setText("-");

        btnDown4.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDown1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDown2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnTester))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTropBas)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(lblDigit1)))
                                    .addComponent(lblExact)
                                    .addComponent(lblTropHaut))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblDigit2))
                                    .addComponent(btnUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnReset)
                                .addGap(83, 83, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblDigit3))
                                    .addComponent(btnUp3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDown3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUp4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDown4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNbEssais)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExact)
                .addGap(5, 5, 5)
                .addComponent(lblTropHaut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTropBas)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUp1)
                    .addComponent(btnUp2)
                    .addComponent(btnUp3)
                    .addComponent(btnUp4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDigit1)
                    .addComponent(lblDigit3)
                    .addComponent(lblDigit4)
                    .addComponent(lblDigit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDown1)
                            .addComponent(btnDown2)
                            .addComponent(btnDown3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTester)
                            .addComponent(btnReset))
                        .addGap(18, 18, 18)
                        .addComponent(lblNbEssais))
                    .addComponent(btnDown4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesterActionPerformed
     ResultatEssai res = jeu.tester(digits);

        lblExact.setText("Exact = " + res.exact);
        lblTropHaut.setText("Trop haut = " + res.tropHaut);
        lblTropBas.setText("Trop bas = " + res.tropBas);
        lblEssais.setText("Essais : " + jeu.getNbEssaisCourants() + "/" + jeu.getNbEssaisMax());

        if (jeu.isPartieTerminee()) {
            JOptionPane.showMessageDialog(this, "Partie terminée !");
        }
    }//GEN-LAST:event_btnTesterActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      jeu = new CadenasJeu(10);
        digits = new int[]{0,0,0,0};
        updateLabels();

        lblExact.setText("Exact = 0");
        lblTropHaut.setText("Trop haut = 0");
        lblTropBas.setText("Trop bas = 0");
        lblEssais.setText("Essais : 0/10");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp1ActionPerformed
     digits[0] = (digits[0] + 1) % 10;
    updateLabels();// TODO add your handling code here:
    }//GEN-LAST:event_btnUp1ActionPerformed

    private void btnUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUp2ActionPerformed
        digits[1] = (digits[1] + 1) % 10;
updateLabels();// TODO add your handling code here:
    }//GEN-LAST:event_btnUp2ActionPerformed
     private void btnUp3ActionPerformed(java.awt.event.ActionEvent evt) {
        digits[2] = (digits[2] + 1) % 10;
        updateLabels();
    }
    private void btnUp4ActionPerformed(java.awt.event.ActionEvent evt) {
        digits[3] = (digits[3] + 1) % 10;
        updateLabels();
    }

    // ----- Boutons − -----
    private void btnDown1ActionPerformed(java.awt.event.ActionEvent evt) {
        digits[0] = (digits[0] + 9) % 10;
        updateLabels();
    }
    private void btnDown2ActionPerformed(java.awt.event.ActionEvent evt) {
        digits[1] = (digits[1] + 9) % 10;
        updateLabels();
    }
    private void btnDown3ActionPerformed(java.awt.event.ActionEvent evt) {
        digits[2] = (digits[2] + 9) % 10;
        updateLabels();
    }
    private void btnDown4ActionPerformed(java.awt.event.ActionEvent evt) {
        digits[3] = (digits[3] + 9) % 10;
        updateLabels();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreCadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown1;
    private javax.swing.JButton btnDown2;
    private javax.swing.JButton btnDown3;
    private javax.swing.JButton btnDown4;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTester;
    private javax.swing.JButton btnUp1;
    private javax.swing.JButton btnUp2;
    private javax.swing.JButton btnUp3;
    private javax.swing.JButton btnUp4;
    private javax.swing.JLabel lblDigit1;
    private javax.swing.JLabel lblDigit2;
    private javax.swing.JLabel lblDigit3;
    private javax.swing.JLabel lblDigit4;
    private javax.swing.JLabel lblExact;
    private javax.swing.JLabel lblNbEssais;
    private javax.swing.JLabel lblTropBas;
    private javax.swing.JLabel lblTropHaut;
    // End of variables declaration//GEN-END:variables

   

